<?php

namespace Money;

class Currency
{
	public $id;
	public $priority;
	public $isoCode;
	public $symbol;
	public $subunit;
	public $subunitToUnit;
	public $symbolFirst;
	public $htmlEntity;
	public $decimalMark;
	public $thousandsSeparator;

	public function __construct($id)
	{
		$this->id = strtolower($id);
		if (!isset(self::$_table[$this->id]))
			throw new \Exception('unknown currency');

		foreach (self::$_table[$this->id] as $k => $v)
			$this->$k = $v;
	}

	/**
	 *
	 * @param type $currency
	 * @return Currency
	 */
	public static function wrap($currency)
	{
		if (is_object($currency))
			return $currency;
		elseif (is_string($currency))
			return new self($currency);
	}

	public function symbolFirst()
	{
		return $this->symbolFirst;
	}

	public function decimalPlaces()
	{
		if ($this->subunitToUnit == 1)
			return 0;
		elseif ($this->subunitToUnit % 10 == 0)
			return floor(log10($this->subunitToUnit));
		else
			return floor(log10($this->subunitToUnit) + 1);
	}

	public function equals($c)
	{
		return $this->id === $c->id;
	}

	public function __toString()
	{
		return strtoupper($this->id);
	}

	private static $_table = array(
		'aed' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AED', 'name' => 'United Arab Emirates Dirham',               'symbol' => 'د.إ',           'subunit' => 'Fils',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'afn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AFN', 'name' => 'Afghan Afghani',                            'symbol' => '؋',             'subunit' => 'Pul',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'all' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ALL', 'name' => 'Albanian Lek',                              'symbol' => 'L',             'subunit' => 'Qintar',        'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'amd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AMD', 'name' => 'Armenian Dram',                             'symbol' => 'դր.',           'subunit' => 'Luma',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ang' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ANG', 'name' => 'Netherlands Antillean Gulden',              'symbol' => 'ƒ',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x0192;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'aoa' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AOA', 'name' => 'Angolan Kwanza',                            'symbol' => 'Kz',            'subunit' => 'Cêntimo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ars' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ARS', 'name' => 'Argentine Peso',                            'symbol' => '$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'aud' => array( 'disambiguator' =>  'A', 'priority' =>   4, 'isoCode' => 'AUD', 'name' => 'Australian Dollar',                         'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'awg' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AWG', 'name' => 'Aruban Florin',                             'symbol' => 'ƒ',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x0192;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'azn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'AZN', 'name' => 'Azerbaijani Manat',                         'symbol' => null,             'subunit' => 'Qəpik',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bam' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BAM', 'name' => 'Bosnia and Herzegovina Convertible Mark',   'symbol' => 'KM or КМ',      'subunit' => 'Fening',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bbd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BBD', 'name' => 'Barbadian Dollar',                          'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',       'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bdt' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BDT', 'name' => 'Bangladeshi Taka',                          'symbol' => '৳',             'subunit' => 'Paisa',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bgn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BGN', 'name' => 'Bulgarian Lev',                             'symbol' => 'лв',            'subunit' => 'Stotinka',      'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bhd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BHD', 'name' => 'Bahraini Dinar',                            'symbol' => 'ب.د',           'subunit' => 'Fils',         'subunitToUnit' => 1000,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bif' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BIF', 'name' => 'Burundian Franc',                           'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bmd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BMD', 'name' => 'Bermudian Dollar',                          'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bnd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BND', 'name' => 'Brunei Dollar',                             'symbol' => '$',             'subunit' => 'Sen',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bob' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BOB', 'name' => 'Bolivian Boliviano',                        'symbol' => 'Bs.',           'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'brl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BRL', 'name' => 'Brazilian Real',                            'symbol' => 'R$',            'subunit' => 'Centavo',      'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'R$',      'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'bsd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BSD', 'name' => 'Bahamian Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'btn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BTN', 'name' => 'Bhutanese Ngultrum',                        'symbol' => null,             'subunit' => 'Chertrum',      'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bwp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BWP', 'name' => 'Botswana Pula',                             'symbol' => 'P',             'subunit' => 'Thebe',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'byr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BYR', 'name' => 'Belarusian Ruble',                          'symbol' => 'Br',            'subunit' => 'Kapyeyka',      'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'bzd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'BZD', 'name' => 'Belize Dollar',                             'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'cad' => array( 'disambiguator' =>  'C', 'priority' =>   5, 'isoCode' => 'CAD', 'name' => 'Canadian Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'cdf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CDF', 'name' => 'Congolese Franc',                           'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'chf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CHF', 'name' => 'Swiss Franc',                               'symbol' => 'Fr',            'subunit' => 'Rappen',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'clp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CLP', 'name' => 'Chilean Peso',                              'symbol' => '$',             'subunit' => 'Peso',       'subunitToUnit' => 1,       'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'cny' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CNY', 'name' => 'Chinese Renminbi Yuan',                     'symbol' => '¥',             'subunit' => 'Fen',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x5713;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'cop' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'COP', 'name' => 'Colombian Peso',                            'symbol' => '$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'crc' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CRC', 'name' => 'Costa Rican Colón',                         'symbol' => '₡',             'subunit' => 'Céntimo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A1;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'cuc' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CUC', 'name' => 'Cuban Convertible Peso',                    'symbol' => '$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'cup' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CUP', 'name' => 'Cuban Peso',                                'symbol' => '$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'cve' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CVE', 'name' => 'Cape Verdean Escudo',                       'symbol' => '$ or Esc',      'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'czk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'CZK', 'name' => 'Czech Koruna',                              'symbol' => 'Kč',            'subunit' => 'Haléř',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'djf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'DJF', 'name' => 'Djiboutian Franc',                          'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'dkk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'DKK', 'name' => 'Danish Krone',                              'symbol' => 'kr',            'subunit' => 'Øre',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'kr&nbsp;',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'dop' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'DOP', 'name' => 'Dominican Peso',                            'symbol' => '$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'dzd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'DZD', 'name' => 'Algerian Dinar',                            'symbol' => 'د.ج',           'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'eek' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'EEK', 'name' => 'Estonian Kroon',                            'symbol' => 'KR',            'subunit' => 'Sent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'egp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'EGP', 'name' => 'Egyptian Pound',                            'symbol' => '£ or ج.م',      'subunit' => 'Piastre',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ern' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ERN', 'name' => 'Eritrean Nakfa',                            'symbol' => 'Nfk',           'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'etb' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ETB', 'name' => 'Ethiopian Birr',                            'symbol' => null,             'subunit' => 'Santim',        'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'eur' => array( 'disambiguator' => null, 'priority' =>   2, 'isoCode' => 'EUR', 'name' => 'Euro',                                      'symbol' => '€',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20AC;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'fjd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'FJD', 'name' => 'Fijian Dollar',                             'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'fkp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'FKP', 'name' => 'Falkland Pound',                            'symbol' => '£',             'subunit' => 'Penny',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gbp' => array( 'disambiguator' => null, 'priority' =>   3, 'isoCode' => 'GBP', 'name' => 'British Pound',                             'symbol' => '£',             'subunit' => 'Penny',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gel' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GEL', 'name' => 'Georgian Lari',                             'symbol' => 'ლ',             'subunit' => 'Tetri',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ghs' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GHS', 'name' => 'Ghanaian Cedi',                             'symbol' => '₵',             'subunit' => 'Pesewa',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B5;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gip' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GIP', 'name' => 'Gibraltar Pound',                           'symbol' => '£',             'subunit' => 'Penny',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gmd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GMD', 'name' => 'Gambian Dalasi',                            'symbol' => 'D',             'subunit' => 'Butut',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gnf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GNF', 'name' => 'Guinean Franc',                             'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gtq' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GTQ', 'name' => 'Guatemalan Quetzal',                        'symbol' => 'Q',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'gyd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'GYD', 'name' => 'Guyanese Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',       'decimalMark' => '.', 'thousandsSeparator' => ','),
		'hkd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'HKD', 'name' => 'Hong Kong Dollar',                          'symbol' => 'HK$ ',             'subunit' => 'Ho',            'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'HK$&nbsp;',       'decimalMark' => '.', 'thousandsSeparator' => ','),
		'hnl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'HNL', 'name' => 'Honduran Lempira',                          'symbol' => 'L',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'hrk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'HRK', 'name' => 'Croatian Kuna',                             'symbol' => 'kn',            'subunit' => 'Lipa',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'htg' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'HTG', 'name' => 'Haitian Gourde',                            'symbol' => 'G',             'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'huf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'HUF', 'name' => 'Hungarian Forint',                          'symbol' => 'Ft',            'subunit' => 'Fillér',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'idr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'IDR', 'name' => 'Indonesian Rupiah',                         'symbol' => 'Rp',            'subunit' => 'Sen',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'ils' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ILS', 'name' => 'Israeli New Sheqel',                        'symbol' => '₪',             'subunit' => 'Agora',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20AA;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'inr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'INR', 'name' => 'Indian Rupee',                              'symbol' => '₨',             'subunit' => 'Paisa',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A8;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'iqd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'IQD', 'name' => 'Iraqi Dinar',                               'symbol' => 'ع.د',           'subunit' => 'Fils',          'subunitToUnit' => 1000, 'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'irr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'IRR', 'name' => 'Iranian Rial',                              'symbol' => '﷼',             'subunit' => 'Dinar',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#xFDFC;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'isk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ISK', 'name' => 'Icelandic Króna',                           'symbol' => 'kr',            'subunit' => 'Eyrir',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'jmd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'JMD', 'name' => 'Jamaican Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'jod' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'JOD', 'name' => 'Jordanian Dinar',                           'symbol' => 'د.ا',           'subunit' => 'Piastre',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'jpy' => array( 'disambiguator' => null, 'priority' =>   6, 'isoCode' => 'JPY', 'name' => 'Japanese Yen',                              'symbol' => '¥',             'subunit' => 'Sen',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x00A5;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kes' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KES', 'name' => 'Kenyan Shilling',                           'symbol' => 'Sh',            'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kgs' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KGS', 'name' => 'Kyrgyzstani Som',                           'symbol' => null,             'subunit' => 'Tyiyn',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'khr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KHR', 'name' => 'Cambodian Riel',                            'symbol' => '៛',             'subunit' => 'Sen',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x17DB;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kmf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KMF', 'name' => 'Comorian Franc',                            'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kpw' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KPW', 'name' => 'North Korean Won',                          'symbol' => '₩',             'subunit' => 'Chŏn',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20A9;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'krw' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KRW', 'name' => 'South Korean Won',                          'symbol' => '₩',             'subunit' => 'Jeon',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A9;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kwd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KWD', 'name' => 'Kuwaiti Dinar',                             'symbol' => 'د.ك',           'subunit' => 'Fils',         'subunitToUnit' => 1000,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kyd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KYD', 'name' => 'Cayman Islands Dollar',                     'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'kzt' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'KZT', 'name' => 'Kazakhstani Tenge',                         'symbol' => '〒',             'subunit' => 'Tiyn',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lak' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LAK', 'name' => 'Lao Kip',                                   'symbol' => '₭',             'subunit' => 'Att',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20AD;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lbp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LBP', 'name' => 'Lebanese Lira',                             'symbol' => 'ل.ل',           'subunit' => 'Piastre',      'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lkr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LKR', 'name' => 'Sri Lankan Rupee',                          'symbol' => '₨',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x0BF9;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lrd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LRD', 'name' => 'Liberian Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lsl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LSL', 'name' => 'Lesotho Loti',                              'symbol' => 'L',             'subunit' => 'Sente',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ltl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LTL', 'name' => 'Lithuanian Litas',                          'symbol' => 'Lt',            'subunit' => 'Centas',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lvl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LVL', 'name' => 'Latvian Lats',                              'symbol' => 'Ls',            'subunit' => 'Santīms',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'lyd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'LYD', 'name' => 'Libyan Dinar',                              'symbol' => 'ل.د',           'subunit' => 'Dirham',       'subunitToUnit' => 1000,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mad' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MAD', 'name' => 'Moroccan Dirham',                           'symbol' => 'د.م.',          'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mdl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MDL', 'name' => 'Moldovan Leu',                              'symbol' => 'L',             'subunit' => 'Ban',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mga' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MGA', 'name' => 'Malagasy Ariary',                           'symbol' => null,             'subunit' => 'Iraimbilanja',  'subunitToUnit' => 5,    'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mkd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MKD', 'name' => 'Macedonian Denar',                          'symbol' => 'ден',           'subunit' => 'Deni',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mmk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MMK', 'name' => 'Myanmar Kyat',                              'symbol' => 'K',             'subunit' => 'Pya',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mnt' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MNT', 'name' => 'Mongolian Tögrög',                          'symbol' => '₮',             'subunit' => 'Möngö',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20AE;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mop' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MOP', 'name' => 'Macanese Pataca',                           'symbol' => 'P',             'subunit' => 'Avo',           'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mro' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MRO', 'name' => 'Mauritanian Ouguiya',                       'symbol' => 'UM',            'subunit' => 'Khoums',        'subunitToUnit' => 5,    'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mur' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MUR', 'name' => 'Mauritian Rupee',                           'symbol' => '₨',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A8;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mvr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MVR', 'name' => 'Maldivian Rufiyaa',                         'symbol' => 'ރ.',            'subunit' => 'Laari',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mwk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MWK', 'name' => 'Malawian Kwacha',                           'symbol' => 'MK',            'subunit' => 'Tambala',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mxn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MXN', 'name' => 'Mexican Peso',                              'symbol' => 'M$',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'M$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'myr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MYR', 'name' => 'Malaysian Ringgit',                         'symbol' => 'RM',            'subunit' => 'Sen',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'mzn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'MZN', 'name' => 'Mozambican Metical',                        'symbol' => 'MTn',           'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'nad' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NAD', 'name' => 'Namibian Dollar',                           'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',       'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ngn' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NGN', 'name' => 'Nigerian Naira',                            'symbol' => '₦',             'subunit' => 'Kobo',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20A6;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'nio' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NIO', 'name' => 'Nicaraguan Córdoba',                        'symbol' => 'C$',            'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'nok' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NOK', 'name' => 'Norwegian Krone',                           'symbol' => 'kr',            'subunit' => 'Øre',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'kr&nbsp;',       'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'npr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NPR', 'name' => 'Nepalese Rupee',                            'symbol' => '₨',             'subunit' => 'Paisa',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A8;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'nzd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'NZD', 'name' => 'New Zealand Dollar',                        'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'omr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'OMR', 'name' => 'Omani Rial',                                'symbol' => 'ر.ع.',          'subunit' => 'Baisa',        'subunitToUnit' => 1000,  'symbolFirst' => true, 'htmlEntity' => '&#xFDFC;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pab' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PAB', 'name' => 'Panamanian Balboa',                         'symbol' => 'B/.',           'subunit' => 'Centésimo',     'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pen' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PEN', 'name' => 'Peruvian Nuevo Sol',                        'symbol' => 'S/.',           'subunit' => 'Céntimo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => 'S/.',      'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pgk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PGK', 'name' => 'Papua New Guinean Kina',                    'symbol' => 'K',             'subunit' => 'Toea',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'php' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PHP', 'name' => 'Philippine Peso',                           'symbol' => '₱',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20B1;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pkr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PKR', 'name' => 'Pakistani Rupee',                           'symbol' => '₨',             'subunit' => 'Paisa',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A8;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pln' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PLN', 'name' => 'Polish Złoty',                              'symbol' => 'zł',            'subunit' => 'Grosz',         'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'pyg' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'PYG', 'name' => 'Paraguayan Guaraní',                        'symbol' => '₲',             'subunit' => 'Céntimo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B2;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'qar' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'QAR', 'name' => 'Qatari Riyal',                              'symbol' => 'ر.ق',           'subunit' => 'Dirham',        'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#xFDFC;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ron' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'RON', 'name' => 'Romanian Leu',                              'symbol' => 'L',             'subunit' => 'Ban',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'rsd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'RSD', 'name' => 'Serbian Dinar',                             'symbol' => 'din. or дин.',  'subunit' => 'Para',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'rub' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'RUB', 'name' => 'Russian Ruble',                             'symbol' => 'р.',            'subunit' => 'Kopek',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x0440;&#x0443;&#x0431;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'rwf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'RWF', 'name' => 'Rwandan Franc',                             'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sar' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SAR', 'name' => 'Saudi Riyal',                               'symbol' => 'ر.س',           'subunit' => 'Hallallah',    'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#xFDFC;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sbd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SBD', 'name' => 'Solomon Islands Dollar',                    'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'scr' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SCR', 'name' => 'Seychellois Rupee',                         'symbol' => '₨',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20A8;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sdg' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SDG', 'name' => 'Sudanese Pound',                            'symbol' => '£',             'subunit' => 'Piastre',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sek' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SEK', 'name' => 'Swedish Krona',                             'symbol' => 'kr',            'subunit' => 'Öre',           'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sgd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SGD', 'name' => 'Singapore Dollar',                          'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'shp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SHP', 'name' => 'Saint Helenian Pound',                      'symbol' => '£',             'subunit' => 'Penny',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'skk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SKK', 'name' => 'Slovak Koruna',                             'symbol' => 'Sk',            'subunit' => 'Halier',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sll' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SLL', 'name' => 'Sierra Leonean Leone',                      'symbol' => 'Le',            'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'sos' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SOS', 'name' => 'Somali Shilling',                           'symbol' => 'Sh',            'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'srd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SRD', 'name' => 'Surinamese Dollar',                         'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'std' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'STD', 'name' => 'São Tomé and Príncipe Dobra',               'symbol' => 'Db',            'subunit' => 'Cêntimo',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'svc' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SVC', 'name' => 'Salvadoran Colón',                          'symbol' => '₡',             'subunit' => 'Centavo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20A1;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'syp' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SYP', 'name' => 'Syrian Pound',                              'symbol' => '£ or ل.س',     'subunit' => 'Piastre',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x00A3;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'szl' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'SZL', 'name' => 'Swazi Lilangeni',                           'symbol' => 'L',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'thb' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'THB', 'name' => 'Thai Baht',                                 'symbol' => '฿',             'subunit' => 'Satang',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x0E3F;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'tjs' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TJS', 'name' => 'Tajikistani Somoni',                        'symbol' => 'ЅМ',            'subunit' => 'Diram',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'tmm' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TMM', 'name' => 'Turkmenistani Manat',                       'symbol' => 'm',             'subunit' => 'Tennesi',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'tnd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TND', 'name' => 'Tunisian Dinar',                            'symbol' => 'د.ت',           'subunit' => 'Millime',       'subunitToUnit' => 1000, 'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'top' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TOP', 'name' => 'Tongan Paʻanga',                            'symbol' => 'T$',            'subunit' => 'Seniti',        'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'try' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TRY', 'name' => 'Turkish New Lira',                          'symbol' => 'YTL',           'subunit' => 'New kuruş',     'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ttd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TTD', 'name' => 'Trinidad and Tobago Dollar',                'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'twd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TWD', 'name' => 'New Taiwan Dollar',                         'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'tzs' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'TZS', 'name' => 'Tanzanian Shilling',                        'symbol' => 'Sh',            'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'uah' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'UAH', 'name' => 'Ukrainian Hryvnia',                         'symbol' => '₴',             'subunit' => 'Kopiyka',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#x20B4', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'ugx' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'UGX', 'name' => 'Ugandan Shilling',                          'symbol' => 'Sh',            'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'usd' => array( 'disambiguator' =>  'U', 'priority' =>   1, 'isoCode' => 'USD', 'name' => 'United States Dollar',                      'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'uyu' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'UYU', 'name' => 'Uruguayan Peso',                            'symbol' => '$',             'subunit' => 'Centésimo',     'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x20B1;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'uzs' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'UZS', 'name' => 'Uzbekistani Som',                           'symbol' => null,             'subunit' => 'Tiyin',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'vef' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'VEF', 'name' => 'Venezuelan Bolívar',                        'symbol' => 'Bs F',          'subunit' => 'Céntimo',       'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'vnd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'VND', 'name' => 'Vietnamese Đồng',                           'symbol' => '₫',             'subunit' => 'Hào',           'subunitToUnit' => 10,   'symbolFirst' => true, 'htmlEntity' => '&#x20AB;', 'decimalMark' => ',', 'thousandsSeparator' => '.'),
		'vuv' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'VUV', 'name' => 'Vanuatu Vatu',                              'symbol' => 'Vt',            'subunit' => null,             'subunitToUnit' => 1,    'symbolFirst' => true, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'wst' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'WST', 'name' => 'Samoan Tala',                               'symbol' => 'T',             'subunit' => 'Sene',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'xaf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'XAF', 'name' => 'Central African Cfa Franc',                 'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'xcd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'XCD', 'name' => 'East Caribbean Dollar',                     'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
		'xof' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'XOF', 'name' => 'West African Cfa Franc',                    'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'xpf' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'XPF', 'name' => 'Cfp Franc',                                 'symbol' => 'Fr',            'subunit' => 'Centime',       'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'yer' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'YER', 'name' => 'Yemeni Rial',                               'symbol' => '﷼',             'subunit' => 'Fils',          'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '&#xFDFC;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'zar' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ZAR', 'name' => 'South African Rand',                        'symbol' => 'R',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '&#x0052;', 'decimalMark' => '.', 'thousandsSeparator' => ','),
		'zmk' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ZMK', 'name' => 'Zambian Kwacha',                            'symbol' => 'ZK',            'subunit' => 'Ngwee',         'subunitToUnit' => 100,  'symbolFirst' => false, 'htmlEntity' => '',         'decimalMark' => '.', 'thousandsSeparator' => ','),
		'zwd' => array( 'disambiguator' => null, 'priority' => 100, 'isoCode' => 'ZWD', 'name' => 'Zimbabwean Dollar',                         'symbol' => '$',             'subunit' => 'Cent',          'subunitToUnit' => 100,  'symbolFirst' => true, 'htmlEntity' => '$',        'decimalMark' => '.', 'thousandsSeparator' => ','),
	);
}
